# Generated by Django 3.0.8 on 2020-07-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200711_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(),
        ),
    ]
