# Generated by Django 3.0.8 on 2020-07-13 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200712_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedepartment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_department', to='core.Employee'),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_leave', to='core.Employee'),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employeeposition',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_position', to='core.Employee'),
        ),
    ]
